### ISSUE TITLE
dussend start timer and dussend say enything in the log channel

### ISSUE THREAD

**Issue by Nailed-it1** [MirageZoe/better-discord-antispam#10]
hi, I just can't figure out why the mute roll doesn't  mute enyone even though all settings are off and it's on top. also i can't change the timer. if I add time, nothing changes and he still "mutes" them for 10 minutes. oh and is it posible to make a channel inmune so ppl can spam init

**Comment by Nailed-it1** [comment]
this is the error im getting

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2896) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (C:\Users\Tycho\Desktop\discortbotuntiteldtv\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
