### ISSUE TITLE
Massive error appears when trying to paste this code in

### ISSUE THREAD

**Issue by opcodesongit** [MirageZoe/better-discord-antispam#19]
Heres the error:

`(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:34) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildChannelManager.create (/home/runner/Group-Manager/node_modules/discord.js/src/managers/GuildChannelManager.js:112:18)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19)
(node:34) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
parent_id: Maximum number of channels in category reached (50)
    at RequestHandler.execute (/home/runner/Group-Manager/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Promise { <pending> }
Error: Cannot find module 'better-discord-antispam'
Require stack:
- /home/runner/Group-Manager/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at /home/runner/Group-Manager/index.js:12:18`

**Comment by MirageZoe** [comment]
From what I have seen so far, discord is telling you that you can't (or the bot) create anymore channels in that category. You have reached the amount of maximum channels which is 50. And about the last thing with "error: cannot find the module 'better-discord-antispam" means either the module is gone or nodejs cannot find it anywhere. To fix u need to reinstall the module with "npm install". If it doesn't fix, try "npm install -g".
